version: "3.8"
services:
  api:
    build: ./api
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY    
    expose:
      - "3001"
      - "8080"
  app:
    build: ./app
    ports: 
      - "3000:80"
