version: "3.8"
services:
  api:
    build: ./api 
    expose:
      - "3001"
      - "8080"
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod      
    ports: 
      - "80:80"  # change this to __port__:80 to change the port on local machine
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
